---
x-default-environment: &default-environment
  {{- with .DefaultEnvironment }}
  ACTION_HOST: {{ .ACTION_HOST }}
  ACTION_PORT: {{ .ACTION_PORT }}
  PRESENTER_HOST: {{ .PRESENTER_HOST }}
  PRESENTER_PORT: {{ .PRESENTER_PORT }}

  DATASTORE_READER_HOST: {{ .DATASTORE_READER_HOST }}
  DATASTORE_READER_PORT: {{ .DATASTORE_READER_PORT }}
  DATASTORE_WRITER_HOST: {{ .DATASTORE_WRITER_HOST }}
  DATASTORE_WRITER_PORT: {{ .DATASTORE_WRITER_PORT }}
  DATASTORE_DATABASE_HOST: {{ .DATASTORE_DATABASE_HOST }}
  DATASTORE_DATABASE_PORT: {{ .DATASTORE_DATABASE_PORT}}
  DATASTORE_DATABASE_NAME: {{ .DATASTORE_DATABASE_NAME }}
  DATASTORE_DATABASE_USER: {{ .DATASTORE_DATABASE_USER }}
  DATASTORE_DATABASE_PASSWORD_FILE: {{ .DATASTORE_DATABASE_PASSWORD_FILE }}

  AUTOUPDATE_HOST: {{ .AUTOUPDATE_HOST }}
  AUTOUPDATE_PORT: {{ .AUTOUPDATE_PORT }}

  AUTH_HOST: {{ .AUTH_HOST }}
  AUTH_PORT: {{ .AUTH_PORT }}

  VOTE_HOST: {{ .VOTE_HOST }}
  VOTE_PORT: {{ .VOTE_PORT }}
  VOTE_DATABASE_HOST: {{ .VOTE_DATABASE_HOST }}
  VOTE_DATABASE_PORT: {{ .VOTE_DATABASE_PORT }}
  VOTE_DATABASE_NAME: {{ .VOTE_DATABASE_NAME }}
  VOTE_DATABASE_USER: {{ .VOTE_DATABASE_USER }}
  VOTE_DATABASE_PASSWORD_FILE: {{ .VOTE_DATABASE_PASSWORD_FILE }}
  VOTE_REDIS_HOST: {{ .VOTE_REDIS_HOST }}
  VOTE_REDIS_PORT: {{ .VOTE_REDIS_PORT }}

  CACHE_HOST: {{ .CACHE_HOST }}
  CACHE_PORT: {{ .CACHE_PORT }}

  MESSAGE_BUS_HOST: {{ .MESSAGE_BUS_HOST }}
  MESSAGE_BUS_PORT: {{ .MESSAGE_BUS_PORT }}

  MEDIA_HOST: {{ .MEDIA_HOST }}
  MEDIA_PORT: {{ .MEDIA_PORT }}
  MEDIA_DATABASE_HOST: {{ .MEDIA_DATABASE_HOST }}
  MEDIA_DATABASE_PORT: {{ .MEDIA_DATABASE_PORT }}
  MEDIA_DATABASE_NAME: {{ .MEDIA_DATABASE_NAME }}
  MEDIA_DATABASE_USER: {{ .MEDIA_DATABASE_USER }}
  MEDIA_DATABASE_PASSWORD_FILE: {{ .MEDIA_DATABASE_PASSWORD_FILE }}
  MEDIA_BLOCK_SIZE: {{ .MEDIA_BLOCK_SIZE }}
  MEDIA_PRESENTER_HOST: {{ .MEDIA_PRESENTER_HOST }}
  MEDIA_PRESENTER_PORT: {{ .MEDIA_PRESENTER_PORT }}

  ICC_HOST: {{ .ICC_HOST }}
  ICC_PORT: {{ .ICC_PORT }}
  ICC_REDIS_HOST: {{ .ICC_REDIS_HOST }}
  ICC_REDIS_PORT: {{ .ICC_REDIS_PORT }}

  MANAGE_HOST: {{ .MANAGE_HOST }}
  MANAGE_PORT: {{ .MANAGE_PORT }}
  MANAGE_AUTH_PASSWORD_FILE: {{ .MANAGE_AUTH_PASSWORD_FILE }}

  INTERNAL_AUTH_PASSWORD_FILE: {{ .INTERNAL_AUTH_PASSWORD_FILE }}

  OPENSLIDES_DEVELOPMENT: "{{ .OPENSLIDES_DEVELOPMENT }}"
  {{- end}}

services:

  {{- with .Services.proxy }}
  proxy:
    image: {{ .ContainerRegistry }}/openslides-proxy:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - client
      - backend
      - autoupdate
      - auth
      - media
      - icc
    {{- end }}
    environment:
      << : *default-environment
    {{- if checkFlag $.EnableLocalHTTPS }}
      ENABLE_LOCAL_HTTPS: 1
      HTTPS_CERT_FILE: /run/secrets/cert_crt
      HTTPS_KEY_FILE: /run/secrets/cert_key
    {{- end }}
    {{- if checkFlag $.EnableAutoHTTPS }}
      ENABLE_AUTO_HTTPS: 1
    {{- end }}
    networks:
      - uplink
      - frontend
    ports:
      - {{ $.Host }}:{{ $.Port }}:8000
    {{- if checkFlag $.EnableLocalHTTPS }}
    secrets:
      - cert_crt
      - cert_key
    {{- end }}
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- with .Services.client }}

  client:
    image: {{ .ContainerRegistry }}/openslides-client:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - backend
      - autoupdate
      - auth
      - media
      - icc
    {{- end }}
    environment:
      << : *default-environment
    networks:
      - frontend
    {{- with .AdditionalContent }}{{ marshalContent . }}{{ end }}
  {{- end }}


  {{- with .Services.backend }}

  backend:
    image: {{ .ContainerRegistry }}/openslides-backend:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
      - postgres
    {{- end }}
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
    secrets:
      - auth_token_key
      - auth_cookie_key
      - internal_auth_password
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- with .Services.datastoreReader }}

  datastore-reader:
    image: {{ .ContainerRegistry }}/openslides-datastore-reader:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - postgres
    {{- end }}
    environment:
      << : *default-environment
      NUM_WORKERS: 8
    networks:
      - datastore-reader
      - postgres
    secrets:
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- with .Services.datastoreWriter }}

  datastore-writer:
    image: {{ .ContainerRegistry }}/openslides-datastore-writer:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - postgres
      - redis
    {{- end }}
    environment:
      << : *default-environment
    networks:
      - datastore-reader
      - datastore-writer
      - postgres
      - redis
    secrets:
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- if checkFlag .DisablePostgres }}{{ else }}{{- with .Services.postgres }}

  postgres:
    image: postgres:11
    environment:
      << : *default-environment
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: openslides
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres
    secrets:
      - postgres_password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}{{- end }}


  {{- with .Services.autoupdate }}

  autoupdate:
    image: {{ .ContainerRegistry }}/openslides-autoupdate:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - redis
    {{- end }}
    environment:
      << : *default-environment
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- with .Services.auth }}

  auth:
    image: {{ .ContainerRegistry }}/openslides-auth:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - redis
    {{- end }}
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}

  {{- with .Services.vote }}

  vote:
    image: {{ .ContainerRegistry }}/openslides-vote:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - backend
      - datastore-reader
      - auth
      - autoupdate
      - redis
    {{- end }}
    environment:
      << : *default-environment
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - postgres
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}

  {{- with .Services.redis }}

  redis:
    image: redis:latest
    command: redis-server --save ""
    environment:
      << : *default-environment
    networks:
      - redis
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- with .Services.media }}

  media:
    image: {{ .ContainerRegistry }}/openslides-media:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - backend
      - postgres
    {{- end }}
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
    secrets:
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- with .Services.icc }}

  icc:
    image: {{ .ContainerRegistry }}/openslides-icc:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - postgres
      - redis
    {{- end }}
    environment:
      << : *default-environment
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - postgres
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}


  {{- with .Services.manage }}

  manage:
    image: {{ .ContainerRegistry }}/openslides-manage:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
    {{- end }}
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
      - redis
    secrets:
      - superadmin
      - manage_auth_password
      - internal_auth_password
    {{- with .AdditionalContent }}{{ marshalContent . }}{{- end }}
  {{- end }}

networks:
  uplink:
  frontend:
    internal: true
  datastore-reader:
    internal: true
  datastore-writer:
    internal: true
  postgres:
    internal: true
  redis:
    internal: true

secrets:
  auth_token_key:
    file: ./secrets/auth_token_key
  auth_cookie_key:
    file: ./secrets/auth_cookie_key
  superadmin:
    file: ./secrets/superadmin
  manage_auth_password:
    file: ./secrets/manage_auth_password
  internal_auth_password:
    file: ./secrets/internal_auth_password
  postgres_password:
    file: ./secrets/postgres_password
{{- if checkFlag $.EnableLocalHTTPS }}
  cert_crt:
    file: ./secrets/cert_crt
  cert_key:
    file: ./secrets/cert_key
{{- end }}
