---
x-default-environment: &default-environment
  {{- marshalContent 2 .DefaultEnvironment }}

services:

  {{- with .Services.proxy }}
  proxy:
    image: {{ .ContainerRegistry }}/openslides-proxy:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - client
      - backend
      - autoupdate
      - auth
      - media
      - icc
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    {{- if checkFlag $.EnableLocalHTTPS }}
      ENABLE_LOCAL_HTTPS: 1
      HTTPS_CERT_FILE: /run/secrets/cert_crt
      HTTPS_KEY_FILE: /run/secrets/cert_key
    {{- end }}
    {{- if checkFlag $.EnableAutoHTTPS }}
      ENABLE_AUTO_HTTPS: 1
    {{- end }}
    networks:
      - uplink
      - frontend
    ports:
      - {{ $.Host }}:{{ $.Port }}:8000
    {{- if checkFlag $.EnableLocalHTTPS }}
    secrets:
      - cert_crt
      - cert_key
    {{- end }}
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- with .Services.client }}

  client:
    image: {{ .ContainerRegistry }}/openslides-client:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - backend
      - autoupdate
      - auth
      - media
      - icc
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - frontend
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{ end }}
  {{- end }}


  {{- with .Services.backend }}

  backend:
    image: {{ .ContainerRegistry }}/openslides-backend:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
      - postgres
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
    secrets:
      - auth_token_key
      - auth_cookie_key
      - internal_auth_password
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- with .Services.datastoreReader }}

  datastore-reader:
    image: {{ .ContainerRegistry }}/openslides-datastore-reader:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - postgres
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - datastore-reader
      - postgres
    secrets:
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- with .Services.datastoreWriter }}

  datastore-writer:
    image: {{ .ContainerRegistry }}/openslides-datastore-writer:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - postgres
      - redis
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - datastore-reader
      - datastore-writer
      - postgres
      - redis
    secrets:
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- if checkFlag .DisablePostgres }}{{ else }}{{- with .Services.postgres }}

  postgres:
    image: postgres:11
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
      POSTGRES_DB: openslides
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres
    secrets:
      - postgres_password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}{{- end }}


  {{- with .Services.autoupdate }}

  autoupdate:
    image: {{ .ContainerRegistry }}/openslides-autoupdate:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - redis
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- with .Services.auth }}

  auth:
    image: {{ .ContainerRegistry }}/openslides-auth:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - redis
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}

  {{- with .Services.vote }}

  vote:
    image: {{ .ContainerRegistry }}/openslides-vote:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - backend
      - datastore-reader
      - auth
      - autoupdate
      - redis
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - postgres
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}

  {{- with .Services.redis }}

  redis:
    image: redis:latest
    command: redis-server --save ""
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - redis
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- with .Services.media }}

  media:
    image: {{ .ContainerRegistry }}/openslides-media:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - backend
      - postgres
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
    secrets:
      - postgres_password
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- with .Services.icc }}

  icc:
    image: {{ .ContainerRegistry }}/openslides-icc:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - postgres
      - redis
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - postgres
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}


  {{- with .Services.manage }}

  manage:
    image: {{ .ContainerRegistry }}/openslides-manage:{{ .Tag }}
    {{- if checkFlag $.DisableDependsOn }}{{ else }}
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
    {{- end }}
    environment:
      << : *default-environment
      {{- with .Environment }}{{ marshalContent 6 . }}{{- end }}
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
      - redis
    secrets:
      - superadmin
      - manage_auth_password
      - internal_auth_password
    {{- with .AdditionalContent }}{{ marshalContent 4 . }}{{- end }}
  {{- end }}

networks:
  uplink:
  frontend:
    internal: true
  datastore-reader:
    internal: true
  datastore-writer:
    internal: true
  postgres:
    internal: true
  redis:
    internal: true

secrets:
  auth_token_key:
    file: ./secrets/auth_token_key
  auth_cookie_key:
    file: ./secrets/auth_cookie_key
  superadmin:
    file: ./secrets/superadmin
  manage_auth_password:
    file: ./secrets/manage_auth_password
  internal_auth_password:
    file: ./secrets/internal_auth_password
  postgres_password:
    file: ./secrets/postgres_password
{{- if checkFlag $.EnableLocalHTTPS }}
  cert_crt:
    file: ./secrets/cert_crt
  cert_key:
    file: ./secrets/cert_key
{{- end }}
