name: CI - Build and Test Service

on: [pull_request]
jobs:
  continuous-tests:
    name: Continuous Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.24

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: go fmt
      run: test -z $(gofmt -l .)

    - name: go vet
      run: go vet ./...

    - name: golint
      run: go install golang.org/x/lint/golint@latest && golint -set_exit_status ./...

    - name: go test
      run: go test -timeout 10s -race ./...

  # This setups and runs the dev/run-tests.sh script
  run-test-script:
    name: Run-tests.sh Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Test
        uses: OpenSlides/OpenSlides/dev/actions/build-and-test-service@main
        with:
          service: manage

  startup:
    name: Building of Go binaries and Docker images and test some Makefile targets
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create manage auth password
      run: echo "password" > manage_auth_password

    - name: Build and start server with golang
      run: |
        go build ./cmd/server
        MANAGE_AUTH_PASSWORD_FILE=manage_auth_password timeout --preserve-status --signal SIGINT 5s ./server

    - name: Build and start manage with golang
      run: |
        go build ./cmd/openslides
        ./openslides

    - name: Build Prod
      uses: OpenSlides/OpenSlides/dev/actions/build-service@main
      with:
        service: manage
        context: prod

    - name: Build and start server with Docker
      run: |
        timeout --preserve-status --signal SIGINT 5s docker run --env MANAGE_AUTH_PASSWORD_FILE=/manage_auth_password --volume $PWD/manage_auth_password:/manage_auth_password openslides-manage
      env:
        DOCKER_BUILDKIT: 1

    - name: Build Dev
      uses: OpenSlides/OpenSlides/dev/actions/build-service@main
      with:
        service: manage
        context: dev

    - name: Start development version of server with Makefile
      run: |
        timeout --preserve-status --signal SIGINT 5s docker run --env MANAGE_AUTH_PASSWORD_FILE=/manage_auth_password --volume $PWD/manage_auth_password:/manage_auth_password openslides-manage-dev
      env:
        DOCKER_BUILDKIT: 1

    - name: Build Tests
      uses: OpenSlides/OpenSlides/dev/actions/build-service@main
      with:
        service: manage
        context: tests

    - name: Run tests with Makefile
      run: make run-tests
      env:
        DOCKER_BUILDKIT: 1